apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "mautic.fullname" . }}-config

data:

  MAUTIC_DB_HOST: {{ .Release.Name }}-mariadb

  MAUTIC_DB_USER: {{ .Values.mariadb.auth.username }}

  MAUTIC_DB_NAME: {{ .Values.mariadb.auth.database }}

  MAUTIC_DB_PORT: "3306"

  DOCKER_MAUTIC_ROLE: "mautic_web"

  MAUTIC_REDIS_HOST: {{ include "mautic.fullname" . }}-redis-master

  MAUTIC_REDIS_PORT: "6379"

  MAUTIC_TRUSTED_PROXIES: {{ .Values.mautic.trustedProxies | toJson | quote }}

  MAUTIC_TRUSTED_HOSTS: {{ .Values.mautic.trustedHosts | toJson | quote }}

  MAUTIC_BASE_URL: https://mautic.wachtell.net