apiVersion: apps/v1

kind: Deployment

metadata:

  name: {{ include "mautic.fullname" . }}

  labels:

    {{- include "mautic.labels" . | nindent 4 }}


spec:

  replicas: {{ .Values.replicaCount }}


  selector:

    matchLabels:

      {{- include "mautic.selectorLabels" . | nindent 6 }}


  template:

    metadata:
      labels:

        {{- include "mautic.selectorLabels" . | nindent 8 }}
      
      annotations:
        checksum/php-opcache: {{ include (print $.Template.BasePath "/php-opcache-configmap.yaml") . | sha256sum }}


    spec:

      containers:

        - name: mautic

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80

          envFrom:
            - configMapRef:
                name: {{ include "mautic.fullname" . }}-config

            - secretRef:
                name: {{ include "mautic.fullname" . }}-secret

          env:
            - name: DOCKER_MAUTIC_ROLE
              value: mautic_web
                        
          volumeMounts:
            - name: mautic-media
              mountPath: /var/www/html/docroot/media

            - name: mautic-config
              mountPath: /var/www/html/config
            
            - name: mautic-data
              mountPath: /var/www/html/var

            - name: php-opcache
              mountPath: /usr/local/etc/php/conf.d/opcache.ini
              subPath: opcache.ini

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 5

      volumes:
        - name: mautic-media
          persistentVolumeClaim:
            claimName: {{ include "mautic.mediaPVC" . }}

        - name: mautic-config
          persistentVolumeClaim:
            claimName: {{ include "mautic.configPVC" . }}
        
        - name: mautic-data
          persistentVolumeClaim:
            claimName: {{ include "mautic.dataPVC" . }}
        
        - name: php-opcache
          configMap:
            name: {{ include "mautic.fullname" . }}-php-opcache