apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: mautic-mautic
  namespace: mautic
  annotations: 
    kubernetes.io/ingress.class: traefik-external

spec:

  entryPoints:
    - websecure

  routes:
    - match: Host(`mautic.wachtell.net`)
      kind: Rule
      services:
        - name: mautic-mautic
          port: 80

  tls:
    secretName: wachtell-net-tls