apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mautic.fullname" . }}-secret

type: Opaque

stringData:

  MAUTIC_DB_PASSWORD: smvnhm2zENvNf5RBS6q45tczIG2sAY

  MAUTIC_REDIS_PASSWORD: 1x68zolq8x8EZXmqETi02m4fE4YAzg

  MAUTIC_REDIS_DSN: "redis://:{{ .Values.redis.auth.password }}@{{ include "mautic.fullname" . }}-redis-master:6379"

  MAUTIC_CACHE_ADAPTER_REDIS: >-
    {"adapter":"cache.adapter.redis","dsn":"redis://:{{ .Values.redis.auth.password }}@{{ include "mautic.fullname" . }}-redis-master:6379"}