apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mautic.fullname" . }}-secret

  labels:
    {{- include "mautic.labels" . | nindent 4 }}

type: Opaque

stringData:

  DATABASE_PASSWORD: "{{ .Values.mariadb.auth.password }}"

  REDIS_PASSWORD: "{{ .Values.redis.auth.password }}"