apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mautic.fullname" . }}-secret

type: Opaque

stringData:

  MAUTIC_DB_PASSWORD: {{ .Values.mariadb.auth.password }}
  MAUTIC_REDIS_PASSWORD: {{ .Values.redis.auth.password }}