{{- if (.Values.serviceAccount.create | default false) }}

apiVersion: v1
kind: ServiceAccount

metadata:

  name: {{ include "mautic.serviceAccountName" . }}

  labels:

    {{- include "mautic.labels" . | nindent 4 }}

{{- end }}